# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AD6rUWG3D8aB_-6sxpUYuu-hKH5IeVy9
"""

import streamlit as st
import pandas as pd
import pickle

# Page configuration
st.set_page_config(page_title="Fraud Shield", layout="centered")
st.title("🛡️ Fraud Shield - Credit Card Fraud Detection")

# Load trained model
@st.cache_data
def load_model():
    with open('fraud_detection_model.pkl', 'rb') as f:
        return pickle.load(f)

model = load_model()

st.markdown("Enter the transaction details to check if it's fraudulent or legitimate.")

# Form to input 28 PCA features + Amount
input_data = {}

with st.form("fraud_form"):
    for i in range(1, 29):
        input_data[f'V{i}'] = st.number_input(f"V{i}", value=0.0)
    input_data['Amount'] = st.number_input("Transaction Amount ($)", value=0.0)

    submitted = st.form_submit_button("🔍 Check for Fraud")

if submitted:
    df_input = pd.DataFrame([input_data])
    prediction = model.predict(df_input)[0]
    prob = model.predict_proba(df_input)[0][1]

    if prediction == 1:
        st.error(f"🚨 Fraudulent Transaction Detected! (Confidence: {prob:.2%})")
    else:
        st.success(f"✅ Legitimate Transaction (Confidence: {1 - prob:.2%})")

    st.caption("Model: XGBoost trained on Kaggle credit card fraud dataset")